rem java -Xmx1024m -classpath lib\aterm-java-1.6.jar;lib\commons-codec-1.5.jar;lib\httpclient-4.1.2.jar;lib\httpcore-4.1.3.jar;lib\icu4j-3.4.4.jar;lib\jena-arq-2.9.0-incubating.jar;lib\jena-core-2.7.0-incubating.jar;lib\jena-iri-0.9.0-incubating.jar;lib\jgrapht-jdk1.5.jar;lib\log4j-1.2.16.jar;lib\pellet-cli.jar;lib\pellet-core.jar;lib\pellet-datatypes.jar;lib\pellet-dig.jar;lib\pellet-el.jar;lib\pellet-explanation.jar;lib\pellet-jena.jar;lib\pellet-modularity.jar;lib\pellet-owlapi.jar;lib\pellet-owlapiv3.jar;lib\pellet-pellint.jar;lib\pellet-query.jar;lib\pellet-rules.jar;lib\pellet-test.jar;lib\slf4j-api-1.6.4.jar;lib\slf4j-log4j12-1.6.4.jar;lib\stax-api-1.0.1.jar;lib\wstx-asl-3.2.9.jar;lib\xercesImpl-2.10.0.jar;lib\xml-apis-1.4.01.jar;bin com.monead.semantic.workbench.SemanticWorkbench

rem java -Xmx2024m -classpath lib\aterm-java-1.6.jar;lib\commons-codec-1.5.jar;lib\httpclient-4.1.2.jar;lib\httpcore-4.1.3.jar;lib\icu4j-3.4.4.jar;lib\jena-arq-2.9.0-incubating.jar;lib\jena-core-2.7.0-incubating.jar;lib\jena-iri-0.9.0-incubating.jar;lib\jgrapht-jdk1.5.jar;lib\log4j-1.2.16.jar;lib\pellet-cli.jar;lib\pellet-core.jar;lib\pellet-datatypes.jar;lib\pellet-dig.jar;lib\pellet-el.jar;lib\pellet-explanation.jar;lib\pellet-jena.jar;lib\pellet-modularity.jar;lib\pellet-owlapi.jar;lib\pellet-owlapiv3.jar;lib\pellet-pellint.jar;lib\pellet-query.jar;lib\pellet-rules.jar;lib\pellet-test.jar;lib\slf4j-api-1.6.4.jar;lib\slf4j-log4j12-1.6.4.jar;lib\stax-api-1.0.1.jar;lib\wstx-asl-3.2.9.jar;lib\xercesImpl-2.10.0.jar;lib\xml-apis-1.4.01.jar;dist\SemanticWorkbench.jar com.monead.semantic.workbench.SemanticWorkbench

rem java -Xmx2024m -classpath lib\aterm-java-1.6.jar;lib\commons-codec-1.6.jar;lib\commons-lang.jar;lib\lib\httpclient-4.2.3.jar;lib\httpcore-4.3.3.jar;lib\icu4j-3.4.4.jar;lib\jcl-over-slf4j-1.6.4.jar;lib\jena-arq-2.11.1.jar;lib\jena-core-2.11.1.jar;lib\jena-iri-1.0.1.jar;lib\jena-sdb-1.4.1.jar;lib\jena-tdb-1.0.1.jar;lib\jgrapht-jdk1.5.jar;lib\log4j-1.2.16.jar;lib\pellet-cli.jar;lib\pellet-core.jar;lib\pellet-datatypes.jar;lib\pellet-dig.jar;lib\pellet-el.jar;lib\pellet-explanation.jar;lib\pellet-jena.jar;lib\pellet-modularity.jar;lib\pellet-owlapi.jar;lib\pellet-owlapiv3.jar;lib\pellet-pellint.jar;lib\pellet-query.jar;lib\pellet-rules.jar;lib\pellet-test.jar;lib\slf4j-api-1.6.4.jar;lib\slf4j-log4j12-1.6.4.jar;lib\stax-api-1.0.1.jar;lib\wstx-asl-3.2.9.jar;lib\xercesImpl-2.11.0.jar;lib\xml-apis-1.4.01.jar;dist\SemanticWorkbench.jar com.monead.semantic.workbench.SemanticWorkbench



java -Xmx4000m -classpath lib\alljar.txt;lib\aterm-java-1.6.jar;lib\commons-codec-1.6.jar;lib\commons-lang.jar;lib\httpclient-4.2.3.jar;lib\httpcore-4.2.2.jar;lib\icu4j-3.4.4.jar;lib\jcl-over-slf4j-1.6.4.jar;lib\jena-arq-2.11.1.jar;lib\jena-core-2.11.1.jar;lib\jena-iri-1.0.1.jar;lib\jena-sdb-1.4.1.jar;lib\jena-tdb-1.0.1.jar;lib\jgrapht-jdk1.5.jar;lib\log4j-1.2.16.jar;lib\pellet-cli.jar;lib\pellet-core.jar;lib\pellet-datatypes.jar;lib\pellet-dig.jar;lib\pellet-el.jar;lib\pellet-explanation.jar;lib\pellet-jena.jar;lib\pellet-modularity.jar;lib\pellet-owlapi.jar;lib\pellet-owlapiv3.jar;lib\pellet-pellint.jar;lib\pellet-query.jar;lib\pellet-rules.jar;lib\pellet-test.jar;lib\slf4j-api-1.6.4.jar;lib\slf4j-log4j12-1.6.4.jar;lib\stax-api-1.0.1.jar;lib\wstx-asl-3.2.9.jar;lib\xercesImpl-2.11.0.jar;lib\xml-apis-1.4.01.jar;dist\SemanticWorkbench.jar com.monead.semantic.workbench.SemanticWorkbench
